### ISSUE TITLE
oscollar6: Anti slide may not work yet

### ISSUE THREAD

**Issue by lickx** [lickx/opencollar-os#11]
We had stripped the SL-specific AO override functions out of oc_anim, which are used to make anti slide happen; but we have not yet put back in the legacy anti slide functionality from OC3.

OpenSim 0.9 compiles with the new SL-specific AO functions but I have yet to test whether they are actually implemented in the simulator. OpenSim 0.8 doesn't compile scripts with those functions hence I had to work around them. I am considering starting a separate os9collar6 branch, anticipating on an upcoming OpenSim 0.9 stable release.

**Comment by lickx** [comment]
I can confirm those AO functions work on OpenSim 0.9 but not OpenSim 0.8. See http://opensimulator.org/mantis/view.php?id=7145

The AO hud of OpenCollar also is intended to work with those functions.

**Comment by lickx** [comment]
Tech preview for OpenSim 0.9 is up at Kinky Hub, including the sub AO with server side AO

**Comment by WendyStarfall** [comment]
Just in case, here is the [point in history](https://github.com/VirtualDisgrace/opencollar/tree/3f96f3640319f8d8752c128977121fb6685d6328/src/ao) with the final release variation of the OpenCollar Six AO that supports ZHAOII overrider methods. OpenSim was one of the reasons why we kept ZHAOII for such a long time. <3
