### ISSUE TITLE
Merge apache licensed scripts into oc_root

### ISSUE THREAD

**Issue by lickx** [lickx/opencollar-os#43]

**Comment by lickx** [comment]
I have my doubts about this one now... I actually like the modularity but 4 scripts will impact the simulator harder. On the other side I don't think we'll be seeing 20 collar wearers in 1 region any time soon in OpenSim.

**Comment by WendyStarfall** [comment]
I'm using a mush of ``oc_root`` (+ some web logic) in the public release branch, and for everyone who loves to tinker, pass out the 4 plugins (already compiled), and then I also have a slimmed down and clean ``oc_root`` combo for role play sims and groups.

Maybe you could add the version control (that you have mentioned in another issue) to the ``oc_update`` script, and only merge ``oc_lock`` and ``oc_stealth`` into ``oc_root``? Then you could add discrete server stuff in ``oc_update`` if required?
